### ISSUE TITLE
Blood issue

### ISSUE THREAD

**Issue by 34-cyrpty** [pa1nki113r/Project_Brutality#386] opened 2020-05-06 16:01 UTC
I dont know if this is known or not but blood doesnt seem to appear on ceilings

**Comment by 34-cyrpty** [comment] 2020-05-06 16:13
also sorry for anyone who already said this, its really hard to find topics that you dont know it even existed

**Comment by JMartinez9820** [comment] 2020-05-06 16:16
Gore hasn't been overhauled completely yet, still currently in an early phase. Also a duplicate of #281.

**Comment by scaryred24** [comment] 2020-05-06 16:18
Please relocate it to there.

**Closed by scaryred24** 2020-05-06 16:18 UTC
