### ISSUE TITLE
Balance issues (minigun, freezer)

### ISSUE THREAD

**Issue by Sagan-Ro** [pa1nki113r/Project_Brutality#822] opened 2022-02-06 15:44 UTC
Quick notes:

Minigun is uncontrollable in *any* firemode.  Nonsensical both from a gameplay perspective, and from the "fact" our hero is supposedly strong enough to tear bones and metal apart with his bare hand but can't hold a gun steady (to say nothing of the actual gyroscopic effect a spinning barrel causes and its steadying effect).  This abominable recoil also defeats about 25 years of Doom as a shooter based on player reaction, and feels like we're doing a Hollywood slow-motion fight sequence (except we're the only ones in slo-mo!)  With the ammo consumption rate, the player also needs to be able to get SOME of their shots on target or why use the Minigun?  The Heavy Machine Gun and DMR are much better for distance (as intended) and shotguns are for up close - the Minigun does neither with excellence but should fulfill both roles capably in a mid-range capacity (which is no longer possible with the insane bouncing aim now, even on the slowest firing mode!)

Freezethrower beam mode has been getting steadily worse with each iteration to the point it's a joke.  Cool effects, but there is no point to use it instead of the explosive.  It *used* to be that beam was more ammo efficient for single enemies and single-deep crowds, with the missile explosion better for large group efficiency and deeply packed enemies (when you couldn't attack enemies behind those in front).

Now beam mode is impossible to aim (again, recoil, from a beam, WHY?), the ammo consumption is doubled, efficiency is down, and it take 5-10 bullets to shatter a frozen enemy vs 1-3 from previous iterations.  Please don't remove it, just make it useful again, as beforehand both missile and beam had their place.  Now it's just missile 100% of the time which is boring.

Just some thoughts.  If nobody cares, I'll fix it in my own versions.

**Comment by D3X1KAXYZ** [comment] 2022-02-06 15:56
this is not a bug. What you do to your own build is up to you. We are currently still working on the weapons and have barely even touched the monsters, so what might be OP or UP (under powered) now may not be in the future.
Also balance is subjective and based on skill level. We thank you for your input and suggestions, however we like to reserve github issues for bugs only. Any suggestions or ideas can be submitted via the public discord. Hope to see you there^^

I shall now close this.

**Closed** 2022-02-06 15:56 UTC
