### ISSUE TITLE
Bug zombieman

### ISSUE THREAD

**Issue by Tomilasquei1** [pa1nki113r/Project_Brutality#232] opened 2019-10-01 00:32 UTC
I'm having a issue with some comands in console. I can't post photos on github so I've posted in the project brutality discord, my name is Tomilasquei. Maybe you can find it in bug reporting channel. Thanks.

**Comment by scaryred24** [comment] 2019-10-06 00:17
You actually can post images but you have to have them embedded and hosted outside of github.

**Comment by JMartinez9820** [comment] 2019-12-11 15:41
Duplicate of #209 if this involves the Zombieman console. I did update the hotfix for it two days ago.
https://mega.nz/#!7n4RQYiA!B4OKLBqtk7LhZxSm1w6HU8v3kSUFnh3KMe5ex8_haQk

**Comment by JMartinez9820** [comment] 2019-12-20 15:49
Should now be fixed in new commit, issue can now be closed

**Closed** 2019-12-20 16:50 UTC
Labels: question
