### ISSUE TITLE
Cannot kick if weapon is reloading

### ISSUE THREAD

**Issue by fctorial** [pa1nki113r/Project_Brutality#334] opened 2020-02-05 23:21 UTC
Melee is needed most when you're out of ammo, but it's not possible to perform kick if the weapon is reloading. Is should be possible to interrupt reloading and perform the kick.

**Comment by JMartinez9820** [comment] 2020-02-05 23:28
You can't kick when reloading a weapon in Brutal Doom as well. This alone has been suggested multiple times already. However, this is a suggestion and not a bug. I recommend posting suggestions in the [Discord](https://discord.gg/2hJxXPc) server instead. I believe this has been taken into consideration already, but not a top priority for the time being.

**Comment by fctorial** [comment] 2020-02-05 23:56
@JMartinez9820 Where should I look in the source code if I want to work on this feature? How is kick implemented in brutal doom? Is it a weapon?

**Comment by fctorial** [comment] 2020-02-10 14:30
@JMartinez9820 It looks like the real issue is that you cannot switch weapons when reloading. So an engine limitation? PB adds a lot of stuff to base doom. Any idea if this could be implemented in zscript?

**Comment by goldenmob72** [comment] 2020-03-02 14:17
@JMartinez9820 can you answer this ^ please ?

**Comment by JMartinez9820** [comment] 2020-03-02 15:08
@goldenmob72 I would say close this issue for now. I don't know how to explain it either.

**Comment by goldenmob72** [comment] 2020-03-02 22:16
@JMartinez9820 Right-O

**Closed by goldenmob72** 2020-03-02 22:16 UTC
