### ISSUE TITLE
My Cacos turn into Pain Elementals on death and I have giant footprints. 

### ISSUE THREAD

**Issue by Dan9001** [pa1nki113r/Project_Brutality#237] opened 2019-10-06 00:14 UTC
Trying this out with the Bella wad and my Cacos turn into PEs on death and my footprints are HUGE. 
![Screenshot_Doom_20190928_004445](https://user-images.githubusercontent.com/56209233/66262394-b2b35880-e7ac-11e9-8ca7-ae0a1dee94f1.png)
![Screenshot_Doom_20190928_004453](https://user-images.githubusercontent.com/56209233/66262395-b2b35880-e7ac-11e9-88e6-aa68957961e5.png)
![Screenshot_Doom_20191005_194320](https://user-images.githubusercontent.com/56209233/66262396-b2b35880-e7ac-11e9-9a9c-f64e322afce5.png)
![Screenshot_Doom_20191005_194322](https://user-images.githubusercontent.com/56209233/66262397-b2b35880-e7ac-11e9-896d-4a1a56cf9027.png)

**Comment by scaryred24** [comment] 2019-10-06 00:18
The first one is a duplicate of #228 therefore will not be logged.

**Comment by goldenmobster** [comment] 2019-12-01 21:23
> The first one is a duplicate of #228 therefore will not be logged.

Yes and The Giant foorprints were resolved [for now] 
Closed

**Closed by goldenmobster** 2019-12-01 21:23 UTC
