### ISSUE TITLE
zoom after reloading

### ISSUE THREAD

**Issue by yeyeyeety** [pa1nki113r/Project_Brutality#536] opened 2020-11-05 02:55 UTC
if you are using the standard rifle and press the reload key while zoomed in, you will stay zoomed in until you either press the reload key, press the zoom key, or fire. this is only with the standard rifle i tested this with every gun in the game that has a zoom feature

**Comment by JMartinez9820** [comment] 2020-11-05 02:57
Duplicate of #520. Please take a look at other opened or closed issues before posting.

**Closed** 2020-11-16 17:23 UTC
