### ISSUE TITLE
Plasma Rifle and Quick Machete Issues

### ISSUE THREAD

**Issue by Buckethell** [pa1nki113r/Project_Brutality#278] opened 2019-12-02 17:51 UTC
If you press "6" when you have the Plasma Rifle equipped, it will switch endlessly to the same weapon.
When you use the quick machete key, a third arm will appear swinging it...

**Comment by JMartinez9820** [comment] 2019-12-02 17:58
Some other weapons doing the endless changing too if another weapon on that slot its in is not available. As for the quick machette, proper sprites for some weapons are not made yet, and is also a duplicate of #194 .

**Closed** 2020-06-09 18:29 UTC
Labels: bug, duplicate
