### ISSUE TITLE
Stuck animation when switching to Assault Rifle

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#569] opened 2020-12-10 20:44 UTC
When switching guns during mid game, there is a chance where the assault rifle animation gets stuck (the one that plays when you switching to it).
I think that this made you **unable** to switch weapons, but I am not 100% sure.

![PB Assault Rifle Reload Bug](https://user-images.githubusercontent.com/55932902/101827353-34fc8280-3afe-11eb-85d2-0b75cec64db9.gif)

I had accidentally triggered this bug while playing *Doom 2* normally with the mod.
I was using the most current master branch version of Project Brutality (last commit = **11/30/20**) on **GZDoom 4.5**.

This bug is similar (to me at least) to one mentioned in **issue #564** but instead with a different animation.

**Comment by JMartinez9820** [comment] 2020-12-10 20:46
Drop the weapon. This is the only way to fix it. The Drop Weapon can be mapped in controls, inventory. Also, how did you replicate this? I tried before but dropping the LMG, but I don't how people are getting this with the DMR. If you have any info on reproducing this bug, please ask me and I will try to take a look at it if I can. Thanks.

**Comment by GeoDash897** [comment] 2020-12-10 21:51
I was testing some more and I found out more about the bug.

Apparently it has to do with the reloading animation of the **UAC-B950 .45 pistol**, specifically the frames where Doomguy **flicks back the top of the pistol** near the end of the animation.

Here is how to do it:
1. Shoot .45 pistol until the clip is empty
2. Reload
3. When the animation for reloading reaches the frames where Doomguy pulls back the top, switch to another weapon.
4. Your weapon is now stuck.

I tested this out with all of the weapons and the ones that are affected by this bug are: **UAC30 DMR**, **UAC41 Carbine**, and the **UAC Compact Sub-Machine Gun**.
(I think this is true, but I'm not 100% sure)
**Switching to any of these weapons causes the bug to occur.**

This bug can be stalled if you switch to a newly acquired weapon (not any of the mentioned above). However, if you switch back to one of the previously mentioned weapons, the bug will occur.

If you switch to one of the previously mentioned weapons (even if the newly acquired weapon animation hasn't been played yet), the bug will occur.

**Switching after pistol reload is finished (Proper Reload)**

![PB Proper Assault Rifle Reload](https://user-images.githubusercontent.com/55932902/101833455-07680700-3b07-11eb-926e-77ba919192c2.gif)


**Switching during flick of pistol reload animation(Bugged Reload)**

![PB Proper Assault Rifle Bugged Reload](https://user-images.githubusercontent.com/55932902/101833146-890b6500-3b06-11eb-9e61-0cfd6fb52f4f.gif)

I can send the video file of my testing if that helps and message me if you need more info.
(Sorry if this sounds confusing, I'm not the best when it comes to wording)

**Comment by JMartinez9820** [comment] 2020-12-10 22:26
I just fixed it on my end. Check my branch here. The reason why that happen was that when doing a full reload on the pistol, there is a token called PBPistolWasEmpty, it needs that token to be taken away or else the animations from another weapon loops. The pistol can also be deselected while the reload animations happen, due to the A_WeaponReady functions they have. I made a small change to the deselect state so that the animation doesn't mess up.
https://github.com/JMartinez9820/Project_Brutality/tree/JMBranch3

**Comment by GeoDash897** [comment] 2020-12-10 22:29
Thanks for the fix!

**Comment by GeoDash897** [comment] 2020-12-10 22:37
I will test it out. Should I close this commit if it works or wait for the branch merge to master?

**Comment by JMartinez9820** [comment] 2020-12-10 23:00
Wait until it's merged into master. Check pull #569

**Comment by Vantablack1834** [comment] 2020-12-11 04:01
Just to add on, there is a work around to fix this problem by dropping your DMR and picking it back up using the GZDOOM drop weapon bind.

**Comment by Vantablack1834** [comment] 2020-12-11 04:01
It won't prevent the bug but it will fix it

**Closed** 2021-01-11 01:20 UTC
