### ISSUE TITLE
Minor Bugs update for latest pb build

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#205] opened 2019-08-05 20:48 UTC
Actually a couple of minor bugs so here they are:

-Mp40 reload sounds are missed

-double jump sounds missed

-(still)akimbo non-upgraded m2 sprites appearing when changing weapons while m2 upgraded

-barrel crash bug still there

-upgraded plasma gun DmR(dark matter rifle) turns into non upgraded plasmagun(just sprite)if you trow a mine, then it will turn into his normal sprite if you shoot/kick etc.

Extra: looks like the motion blur affects sometimes the gameplay, this means a suddenly crash while you turn faster to shoot a bunch of enemies, this just happens sometimes.

**Comment by MekBoss** [comment] 2019-08-06 11:28
Extra: looks like the motion blur affects sometimes the gameplay, this means a suddenly crash while you turn faster to shoot a bunch of enemies, this just happens sometimes.

Post runnable sample with this bug or way to 100% chance recreate crash.

**Comment by scaryred24** [comment] 2019-08-06 14:39
If we don't have instructions to recreate the bug, then we can't exactly fix it. We certainly don't want to run around headless trying to figure out what went wrong if we don't have any steps to recreate it or any hard evidence that it is causing problems. For now I'd suggest turning off motion blur until it is resolved. As for the rest of them, the barrel crash is a duplicate of #182. The rest have not been discovered.

**Comment by JMartinez9820** [comment] 2019-09-01 19:05
The MP40 Reload sounds, akimbo non-upgraded m2 sprites appearing when changing weapons while m2 upgraded, and barrel crash bug are being fixed by upcoming pull requests. Take a look at pull requests #213 and #214 if needed.

**Comment by JMartinez9820** [comment] 2019-11-22 19:07
Updates to bugs mentioned here.
1. Resolved.
2. Resolved.
3. Recently resolved.
4. Resolved.
5. Not fixed yet
Extra: Can you please share some steps on how to replicate this problem? We this, the team won't know anything that goes wrong. Scaryred suggests to turn off motion blur for now.

**Comment by JMartinez9820** [comment] 2020-04-21 23:49
This issue can now be closed, I think everything has been fixed.

**Closed** 2020-08-07 14:14 UTC
Labels: bug
