### ISSUE TITLE
Severe Performance Degradation

### ISSUE THREAD

**Issue by dbrickshaw** [pa1nki113r/Project_Brutality#92] opened 2019-01-04 18:05 UTC
I'm experiencing an issue where PB causes extreme stuttering / fps loss, but only on certain megawads. Performance is normal when first starting a map, but over time a stuttering / fps drop appears. This stuttering / fps drop gets continually worse over time, and within about 2 minutes of entering the map it becomes an unplayable slideshow.

This issue doesn't occur with the vanilla Doom map sets, and I don't know enough about megawads to isolate what characteristic of the megawad triggers the issue. I've been able to reliably reproduce it using Eviternity RC1 (https://www.doomworld.com/forum/topic/103425-release-eviternity-rc1/) with the following setup:

Loader: ZDL
Source Port: GZDoom 3.7.1 Modern x64
OS: Windows 7 x64

WAD Load Order:
- Eviternity-RC1.wad
- ProjectBrutality.pk3 (latest master version, commit b659c13b5981ca530bc7b14939f8c45773094907)

IWAD:
- doom2.wad

Project Brutality game mode, Brutal difficulty.

The issue will occur on MAP01. This issue does not occur with the PB 3.0 public test version from January 2018.

**Comment by CollegiaTitanica** [comment] 2019-01-04 22:41
not our fault. The problem is the constant spawning of raindrop actors.Map needs to delete the actors, GarbageCollector. Compatibility wise, one would need to recreate the droplet actor,replace the default with it , give it a max timer of like 2 seconds, and have it disappear or something.

Confirm this by typing "actorlist", wait a few seconds and repeat.You'll see what I mean

**Comment by alexcraig** [comment] 2019-01-05 00:21
What am I looking for in the actorlist to confirm that this is the issue?

Valiant MAP01 is another map that has this problem. There's no rain effect on this map, and I'm not seeing a relationship between the number of actors and the fps loss.

I did an experiment where I left my character motionless at the spawn point of Valiant MAP01, and recorded my FPS and number of actors every 10 seconds of game time:

| Game time | FPS | Number of Actors |
|---|---|---|
| 0:10 | | |
| 0:10 | | |
| 0:10 | | |

**Comment by alexcraig** [comment] 2019-01-05 00:36
What am I looking for in the actorlist to confirm that this is the issue?

Valiant (https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/valiant) is another megawad where I experience this problem. There's no rain effect on this map, and I'm not seeing a relationship between the number of actors and the fps loss.

I did an experiment where I left my player motionless at the spawn point of Valiant MAP01, and recorded my FPS and number of actors every 10 seconds of game time:

| Game time | FPS | Number of Actors |
|---|---|---|
| 0:10 | 200 | 1528 |
| 0:20 | 148 | 1548 |
| 0:30 | 101 | 1554 |
| 0:40 | 82 | 1551 |
| 0:50 | 66 | 1548 |
| 0:60 | 55 | 1548 |
| 1:00 | 47 | 1554 |
| 1:10 | 35 | 1554 |
| 1:20 | 35 | 1567 |
| 1:30 | 24 | 1548 |
| 1:40 | 20 | 1536 |

If I run the same experiment with the January 2018 PB public test version my FPS holds steady at 200 fps.

**Comment by alexcraig** [comment] 2019-01-05 01:30
OS: Windows 7 Professional x64
Processor: i7-4770
RAM: 16 GB DDR3
GPU: GTX 1080
Source Port: GZDoom 3.7.1 Modern x64

**Comment by Cacodemon345** [comment] 2019-01-05 05:58
Yes, that commit seems to be the culprit of severe performance degradation. It needs to be redone.

**Comment by Cacodemon345** [comment] 2019-01-05 09:06
Ok, it's a matter of waiting for a PR merge.

**Comment by tunbridgep** [comment] 2019-03-25 09:19
I am playing Eviternity RC1, and having no issues.

However, I was having issues with the game in-general because it was loading from such a large archive.

What I did was split out the SPRITES and SOUNDS folder into seperate archives, change all archives to use a compression level of 0, and the game ran a lot better.

This is likely NOT the source of your issues, but it might help you get some decent performance boosts, at least enough to keep playing those levels for a bit longer

**Comment by scaryred24** [comment] 2020-01-05 04:34
Issue kept open for far longer than I'd originally had anticipated. If one may let me know weather or not this is ongoing do open this back up again. Otherwise I'm closing it until it can be fixed at a later point in development.

**Closed by scaryred24** 2020-01-05 04:34 UTC
Labels: good first issue

**Comment by Saantak** [comment] 2022-07-06 23:42
Encountered this issue today as described above on Requiem WAD Map 21. Is there a fix available?
