### ISSUE TITLE
plasma gun sprite bug

### ISSUE THREAD

**Issue by yeyeyeety** [pa1nki113r/Project_Brutality#387] opened 2020-05-06 16:11 UTC
ledge grab and then pull up with the plasma gun upgrade it reverts back to the original sprite until you fire it

**Comment by JMartinez9820** [comment] 2020-05-06 16:15
Duplicate of #163. Pulse Cannon not overhauled yet.

**Comment by JMartinez9820** [comment] 2020-05-07 00:16
This issue can be closed, as its a duplicate of #163.

**Closed** 2020-05-10 19:54 UTC
