### ISSUE TITLE
The Rifle can reload indefinitely. 

### ISSUE THREAD

**Issue by USEC-WHISKEY** [pa1nki113r/Project_Brutality#571] opened 2020-12-11 14:28 UTC
https://streamable.com/jgi63d

**Comment by JMartinez9820** [comment] 2020-12-11 14:30
Duplicate of #569 and #564. Current way to fix this is to drop weapon, just map a key to drop weapon in controls/inventory if not mapped. Otherwise, check pull #566. Please take a look at other issues before posting any duplicates.

**Closed** 2021-01-11 01:20 UTC
Labels: duplicate
