### ISSUE TITLE
[Minor] It is possible to enqueue actions when holding a meat shield

### ISSUE THREAD

**Issue by Penaz91** [pa1nki113r/Project_Brutality#479] opened 2020-08-30 16:46 UTC
As the title says, having a meat shield allows to enqueue actions that will be performed after the meat shield is dropped.

Steps to reproduce:
1. Shoot any soldier/imp until they're dying
2. Grab them to use them as a meat shield
3. Enqueue a grenade throw and a knife/machete slice
4. Drop the shield
5. After dropping the shield the game will automatically throw a grenade and perform a machete slice.

This was tested on commit e70fde7.

I'm not sure this is a bug, but just in case I'm opening an issue.

Thank you all kindly for your work. I really love this mod!

**Comment by JMartinez9820** [comment] 2020-08-30 16:50
@Penaz91 Its due to how the meatshields work, Brutal Doom itself does it as well. Confirmed to be a minor bug. However, at the meantime meatshields are not a focus. Meatshields will be overhauled way later in development, currently how they are handled is hacky.

**Comment by JMartinez9820** [comment] 2022-09-09 04:41
Update:
Meatshields are possibly going to be scrapped in the future, so I will close this for now.

**Closed by JMartinez9820** 2022-09-09 04:41 UTC
Labels: minor priority
