### ISSUE TITLE
Health Regeneration Doesnt Work Anymore

### ISSUE THREAD

**Issue by Sibbs** [pa1nki113r/Project_Brutality#537] opened 2020-11-07 23:34 UTC
Health Regeneration Doesnt Work Anymore, tried turning it off and on, just doesnt work anymore, i havent updated this since feb, but i can confirm it worked on feb's version, if you can point me in the right direction, maybe i can replace the code with feb's code

**Comment by D3X1KAXYZ** [comment] 2020-11-07 23:36
The health regeneration functionality has been removed, despite the option still being in the menu.

**Comment by JMartinez9820** [comment] 2020-11-07 23:37
This is also a duplicate of #526 and #382. Please check the issue tracker, open or closed, before posting an issue here.

**Comment by JMartinez9820** [comment] 2020-11-07 23:39
For health regen, this [health regeneration mod] (https://forum.zdoom.org/viewtopic.php?f=37&t=47788) can be used instead.

**Comment by Sibbs** [comment] 2020-11-07 23:39
Thanks.

**Closed** 2020-11-07 23:39 UTC
