### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#254] opened 2019-11-09 05:18 UTC
I know I shouldn't post this here but I can't post in discord and don't know how to fix it.
When I go there I see the message: 

You do not have permission to send messages in this channel.

**Comment by JMartinez9820** [comment] 2019-11-09 05:26
This issue is not related to PB, and is a duplicate of #238. A bot should have sent you a DM on Discord for verification. If you just created a Discord account, then your account is too young and won't join until a span of 3 days. Otherwise, check Scaryred24's message in #252 for more information.

**Comment by goldenmob72** [comment] 2019-11-10 03:55
This should be closed

**Closed** 2019-11-10 04:04 UTC
