### ISSUE TITLE
Incompatibility with HD texture pack?

### ISSUE THREAD

**Issue by SebRW** [pa1nki113r/Project_Brutality#306] opened 2020-01-09 15:18 UTC
Hi, 

I'm comparing the PB 3.0 beta build from last year and the current one (PB 3.0 master).
Using the same HD texture pack I noticed that some map enhancement does not work on 3.0 master. 
Here are 2 examples:
**1- Grass & window texture + vehicle:**
3.0 beta: https://i.ibb.co/94PWLdb/PB3-0beta.png
3.0 master: https://i.ibb.co/Wz1ZvC5/PB3-0master.png

**2- Little rotative light on the roof:**
3.0 beta: Hi, 

I'm comparing the PB 3.0 beta build from last year and the current one (PB 3.0 master).
Using the same HD texture pack I noticed that some map enhancement does not work on 3.0 master. 
Here are 2 examples:
**1- Grass & window texture + vehicle:**
3.0 beta: https://i.ibb.co/94PWLdb/PB3-0beta.png
3.0 master: https://i.ibb.co/Wz1ZvC5/PB3-0master.png

**2- Little rotative light on the roof:**
3.0 beta: https://i.ibb.co/wC6jf5r/PB3-0beta2.png
3.0 master: https://i.ibb.co/CsBK0xg/PB3-0master2.png

This seems not to be linked with PB map enhancement as disabling this feature does not change anything.

**Comment by scaryred24** [comment] 2020-01-09 15:35
Duplicate of #263. Please do not open reports that already exists.

**Closed by scaryred24** 2020-01-09 15:35 UTC
