### ISSUE TITLE
Cant seem to move no matter what I do 

### ISSUE THREAD

**Issue by Thatguy8888** [pa1nki113r/Project_Brutality#460] opened 2020-08-12 22:44 UTC
Hey never even been on github before so dont know if iam doing this right anyway, I cant seem to move no matter what I have tried rebinding and reinstalling project brutality 3.0 but no matter what I cant move. Also seems like im not the only one with this issue  (  https://www.reddit.com/r/brutaldoom/comments/h9mj1k/project_brutality_30_player_cannot_move_in_any/ )
 I'm out of ideas on how to fix this.

**Comment by popguy12** [comment] 2020-08-12 22:46
have you tried backing up and resetting your ini file?

**Comment by scaryred24** [comment] 2020-08-12 23:43
Silly question but do you have discord overlay turned on?

**Comment by Thatguy8888** [comment] 2020-08-14 20:18
> Silly question but do you have discord overlay turned on?

no I dont use discord that much and I checked I dont.

**Comment by goldenmob72** [comment] 2020-08-14 20:27
Are you sure about that ?  
Please provide evidence

**Comment by JMartinez9820** [comment] 2020-08-14 20:29
If that's the case, then my only recommendation is to the delete the gzdoom.ini/lzdoom.ini for a fresh new one.

**Comment by goldenmob72** [comment] 2020-08-14 20:31
I find it hard to believe that the Discord overlay is showing up, even thought you have it on

**Comment by goldenmob72** [comment] 2020-08-14 20:33
Sorry, typos

**Comment by scaryred24** [comment] 2020-08-14 20:52
> 
> 
> I find it hard to believe that the Discord overlay is showing up, even though you have it off

Even if it doesn't show up its still on and thus can mess with it. The choices would either have been to turn off overlays entirely or remove the program from the list after being auto-detected. Since Discord wasn't running at the time these problems arisen it can be safely be ruled out.

**Comment by goldenmob72** [comment] 2020-08-15 15:04
That being said, that's a Discord issue, not a PB issue
Issue is now closed until further notice

**Comment by Thatguy8888** [comment] 2020-08-15 17:56
what ever thanks for the damn help ( fuck this )

**Comment by scaryred24** [comment] 2020-08-15 19:08
> 
> 
> That being said, that's a Discord issue, not a PB issue


You didn't read didn't you?  It's neither an issue with PB nor Discord. However until the problem is resolved or can not be replicated no threads are to be closed until a conclusion is met. 




> 
> 
> what ever thanks for the damn help

No need to be hostile. This attitude would lock the thread. I'd rather to help you than to settle on a unrelated conclusion. 


There was no reason to close this down. Seems to be a miscommunication issue. This is being corrected offsite but as for right now I'm reopening this.

**Comment by Thatguy8888** [comment] 2020-08-15 19:14
> > That being said, that's a Discord issue, not a PB issue
> 
> You didn't read didn't you? It's neither an issue with PB nor Discord. However until the problem is resolved or can not be replicated no threads are to be closed until a conclusion is met.
> 
> > what ever thanks for the damn help
> 
> No need to be hostile. This attitude would lock the thread. I'd rather to help you than to settle on a unrelated conclusion.
> 
> There was no reason to close this down. Seems to be a miscommunication issue. This is being corrected offsite but as for right now I'm reopening this.

sorry for being hostile its just I used to love playing this mod so its frustrating.

**Comment by scaryred24** [comment] 2020-08-15 19:20
Okay take a few steps back. Did you delete the ini file that gets generated on the first boot of GZDoom? Also mind telling me what version you are using?

**Comment by Thatguy8888** [comment] 2020-08-15 19:39
> Okay take a few steps back. Did you delete the ini file that gets generated on the first boot of GZDoom? Also mind telling me what version you are using?

I removed my configuration file and I can move again I tried it before and it did nothing but it worked this time thanks  ( sorry for taking a bit to respond I was making noodles )

**Comment by scaryred24** [comment] 2020-08-15 19:43
Its fine we all have lives to deal with. Glad that fixed the problem. If it happens again don't hesitate to open it back up or leave a response.

**Closed** 2020-08-15 19:43 UTC

**Comment by goldenmob72** [comment] 2020-08-15 20:15
I'm sorry for what I said/typed, I didn't mean it
My bad man
