### ISSUE TITLE
crash issue when loading saves and starting a game

### ISSUE THREAD

**Issue by funnymanDELUXE** [pa1nki113r/Project_Brutality#341] opened 2020-03-01 17:56 UTC
so ive figured it out, all those odd bugs with everything going super fast is caused by this:

if you move your mouse/aim during loading a save or beginning a new game, the game will go super fast and crash. not too sure why this is but this is the main cause

tested on gzdoom 4.3.3, and project brutality without any other addons

**Comment by JMartinez9820** [comment] 2020-03-01 18:01
I believe that this is a GZDoom problem? When I loaded a save from an older version the program crashes, LZDoom has no such issue. I would try using LZDoom, and/or other mods as well to see if this issue happens as well.

**Comment by JMartinez9820** [comment] 2020-03-01 18:08
One more thing, do you have any steps to reproduce this problem? I've tried your advice above and it didn't bug out. Please give proper and clear advice as well.

**Comment by goldenmob72** [comment] 2020-03-04 01:54
@funnymanDELUXE

**Comment by funnymanDELUXE** [comment] 2020-03-08 03:23
super late, but basically once you load in a game just start moving your mouse however you want. it should replicate the bug and crash to console giving the gzdoom fatal error, i can provide a video if needed.

1. start game/load save
2. move mouse while its loading, usually when you move your mouse in advance before the save/game is fully loaded will make the crash happen

**Comment by JMartinez9820** [comment] 2020-04-22 00:06
@funnymanDELUXE I was unable to replicate this problem. This must be a problem on your end. This issue can be closed, otherwise keep it open in needed.

**Comment by SyborgMars54** [comment] 2020-04-26 06:32
@JMartinez9820 it's not just a problem on his end i managed to do something like that except after that i couldn't move, shoot or do anything except pause and leave the game that's when i got the error report message telling me that my game crashed. it shares similarities to a similar bug i had.

**Comment by SyborgMars54** [comment] 2020-04-27 03:26
in fact i managed to replicate it during ending a level and it crashed exactly how he said it. by moving the mouse.

**Comment by JMartinez9820** [comment] 2020-04-27 04:00
Unable to replicate this issue. This thread can be closed. I would try a dev build of GZDoom or LZDoom to see if this problem persists. This is not a priority right now. If the problem persists on the dev builds of GZDoom or LZDoom, then re-open it.

**Comment by lord-andre** [comment] 2020-05-16 02:02
So here are my findings:
I tested GZDoom and LZDoom in the stable and current development version. (May 16, 2020).

Version 4.3.3 (from GZDoom) and (LZ 3.85) do not always crash immediately, sometimes loading ends in a game world that is much too fast. The last development version seems to be a little different, it always crashes immediately. I've also tested other maps or gameplay mods. Vanilla Doom too. No problems here (!!!).

--- How to re-create the problem: ---
Start a new game with PB, and BEFORE answering the last question (regarding difficulty), start moving the mouse. I make circular movements. Clockwise or counterclockwise, it doesn't matter.
 -> With GZDoom, version 4.3.3, the game should now crash.

If you wait a bit (until the melt screen is about 40% done ...) and THEN move the mouse [or move the mouse SLOWLY during the loading time], the new level or the saved game will run a lot off too quickly.

Player input will be ignored from this point on. Except for horizontal mouse movements. (Or escape, console, etc. ...) GZDoom can no longer even save the game!

It appears that certain movement keys or mouse inputs are repeated on their own. Even after death, the level is sometimes restarted on its own!

I would never have found this error myself, because I don't move my mouse during the loading time ...

I'm trying to upload a video of the error:
(The first time I loaded it, I was too slow with the mouse ... After that, there was NO input from me! The process happened on its own!) (Apart from the level change ...)

***
Video:
https://youtu.be/K20Mv_fOwwA
***

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Additional error messages:
From the console: (GZDoom)

  - Sometimes = "GetPacket: NOTINITIALISED"
  - Or nothing! (no error shown)

From the crash report:
Example 1
Code: C0000005 (Access Violation - tried to read address 00007FF8A5B159D0 [or random number])
Address: 00007FF99DDBABCA (or random)

Example 2
Code: C0000005 (Access Violation - tried to read address FFFFFFFFFFFFFFFF)
Address: (random)

Example 3
Code: C0000094 (Integer Divide By Zero)
Address: (random)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Do you need more error data? I am glad to help!

**Comment by JMartinez9820** [comment] 2020-05-16 03:08
Can you try this out with other mods too @lord-andre ? I was still unable to replicate this issue. I have a feeling this should be closed if it can't be replicated properly by the devs too. Please see if this happens with other mods too. Thanks.

**Comment by JMartinez9820** [comment] 2020-05-16 03:11
Also, try replicating this with PB and other mods with LZDoom too. Thanks.

**Comment by SyborgMars54** [comment] 2020-05-16 03:15
What do you mean other mods?

**Comment by JMartinez9820** [comment] 2020-05-16 03:16
@SyborgMars54 Like Brutal Doom, Complex Doom, Beautiful Doom, Final Doomer, Trailblazer, Russian Overkill, Guncaster, etc..

**Comment by SyborgMars54** [comment] 2020-05-16 03:17
well i have never had problems like this on those mods it is only this one.

**Comment by JMartinez9820** [comment] 2020-05-16 03:18
Bizarre. Unfortunately, if this can not be replicated properly by the devs, you're pretty much out of luck and this will be applied to "will not fix". Same thing for you too @lord-andre. I was unable to replicate this myself.

**Comment by SyborgMars54** [comment] 2020-05-16 03:19
WELL hang on a minute what did you test it with?

**Comment by SyborgMars54** [comment] 2020-05-16 03:20
because he clearly states that he was able to replicate it so how is it that you can't.

**Comment by scaryred24** [comment] 2020-05-16 03:21
Keep this open for now. This seems like a serious issue.

**Comment by SyborgMars54** [comment] 2020-05-16 03:21
what did you use lz doom/GZ doom/ GZdoom development build?

**Comment by SyborgMars54** [comment] 2020-05-16 03:21
it was serious long before that

**Comment by JMartinez9820** [comment] 2020-05-16 03:21
I used LZDoom and GZDoom 4.3.3. Every attempt I tried it just loaded properly. I guess I'm just lucky.

**Comment by SyborgMars54** [comment] 2020-05-16 03:26
you what how about i send my copy of the folder i had for regular gz doom and pb 3.0

**Comment by SyborgMars54** [comment] 2020-05-16 03:27
or send the config

**Comment by SyborgMars54** [comment] 2020-05-16 03:37
Because i don't know how or what it is that has you not replicating the problem? either it has something to do with you config or something?

**Comment by SyborgMars54** [comment] 2020-05-16 03:41
did you use zdl?

**Comment by SyborgMars54** [comment] 2020-05-16 03:42
like what's your config for pb

**Comment by SyborgMars54** [comment] 2020-05-16 03:44
Because i find it baffling that you haven't been able to replicate it?

**Comment by SyborgMars54** [comment] 2020-05-16 03:44
is there another person that could try to replicate it?

**Comment by JMartinez9820** [comment] 2020-05-16 03:46
I really don't know what causes this bizarre error and that it could be related to hardware I guess. I suspect that there is a coding error or memory leak in the fading out when starting a new game. I think the fade-out should be removed, we are trying to get other developers behind closed doors to replicate this problem.

**Comment by SyborgMars54** [comment] 2020-05-16 03:50
wait what is the setting on fade out?

**Comment by lord-andre** [comment] 2020-05-16 17:24
Here are other points:

1. Deactivating the screen melt effect under [Options] -> [Display] prevents the error from occurring to me.

2. I have tested an old version of PB 3.0, download date 18.08.2019. 
With this version the error cannot be reproduced. From December 2019 on it can.

3. The error does not appear on my laptop! I had taken the settings from my desktop computer. 
So the problem seems to be partly hardware related.

4. The differences between the individual source ports for me:
GZDoom 4.3.3: Crash or speed-up (as seen in the video)
GZDoom dev-build: mostly crashes, rarely speed-up
LZDoom 3.85: just crashes & no error shown
LZDoom dev-build: just crashes & no error shown

5. Other Mods tested: (no problem)
Brutal Doom
Guncaster
Russian Overkill

**Comment by SyborgMars54** [comment] 2020-05-17 04:25
still i hope this doesn't get closed because it's that much of an occurring problem that it gets frustrating to play to point of it being game breaking bug.

**Comment by Cacodemon345** [comment] 2020-05-18 09:14
Looks like a bug with GZDoom's melt screen effect.

We need to look into the ZScript code why this happens.

This will also require a debugging session with GZDoom dev-builds. Looking for mod bugs without GZDoom's assistance is hard though...

**Comment by Cacodemon345** [comment] 2020-05-18 09:15
Also, does this problem happen with ZMovement?

**Comment by JasonM2396** [comment] 2020-05-18 13:21
@lord-andre @SyborgMars54 Can both of y'all replicate this problem again? I just want to know if y'all get a Fatal Error and check to see if a crash log has been made (gzdoom-crash). If so, can y'all please post it here? Thank you very much. Check the ZMovement thread if necessary.

**Comment by JMartinez9820** [comment] 2020-05-18 13:25
Can y'all why it goes very fast too? Turn on the speedometer to see if a value change is made or not. Its in the Visual Settings in the Project Brutality settings; or type zm_speedometer 1 in the console.

**Comment by SyborgMars54** [comment] 2020-05-18 14:01
well i just crashed and i didn't get a crashlog

**Comment by SyborgMars54** [comment] 2020-05-18 14:03
speedometer was on can't even record speed if i keep crashing

**Comment by SyborgMars54** [comment] 2020-05-18 14:06
[CrashReport.zip](https://github.com/pa1nki113r/Project_Brutality/files/4644569/CrashReport.zip)
here is the crsh report i got when i tried to play normally

**Comment by SyborgMars54** [comment] 2020-05-18 14:08
i noticed that when strafing the speed goes up to 200 on a full strafe

**Comment by JMartinez9820** [comment] 2020-05-18 14:20
> i noticed that when strafing the speed goes up to 200 on a full straferun in doom units

That's normal since the default ground speed is set at 150 (or 15 in ZMovement cvar). You can decrease this by typing pb_maxgroundspeed (any value below 15). Or if you want to decrease the strafe speed, type pb_strafemodifier (Use decimals on this, I don't recommend anything than 1.33, and 1 will be the same speed as regular movement)

**Comment by JMartinez9820** [comment] 2020-05-18 14:22
For example:
> pb_strafemodifier 1.25
> pb_maxgroundspeed 14.5

**Comment by Cacodemon345** [comment] 2020-05-18 15:32
Suggestion: turn on `vid_fps` CVAR before reproducing the bug, and check what it reports. Post the results here.

**Comment by SyborgMars54** [comment] 2020-05-18 15:44
well the speedometer was on before the bug was attempted to replicate

**Comment by Cacodemon345** [comment] 2020-05-18 17:05
`zm_speedometer` is different from `vid_fps`. The former is a mod feature, the latter is an engine feature.

**Comment by Cacodemon345** [comment] 2020-05-18 18:16
Also, comment out the "AddEventHandlers" line one by one in the ZMAPINFO and see if the bug happens.

Can't reproduce from my side, but the crash logs seems to be indicative of a GPU-related hardware issue. Can you guys give us the hardware specs?

**Comment by lord-andre** [comment] 2020-05-19 00:03
0. Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 18362)
Processor: Intel i7-4790K CPU
Graphic Card: AMD Radeon R9 280x
Memory: 16GB RAM

1. @Cacodemon345
Vanilla + ZMovement (from https://forum.zdoom.org/viewtopic.php?f=43&t=65095)
= no error

2. Here are 3 error reports with different error messages:

[3x_CrashReport.zip](https://github.com/pa1nki113r/Project_Brutality/files/4647381/3x_CrashReport.zip)

Different effects of mouse movement:
Tested several times, can be reproduced in this way, in my case, again and again. I hope the information is helpful and does not confuse any further…
Now I've had enough of the constant starting and crashing :sweat_smile:
```

Mouse movement immediately at start:
-Horizontal = Immediate crash, no error message
-Vertical = error message: Code: C0000094 (Integer Divide By Zero)
-Circular clockwise = Code: C0000005 (Access Violation - tried to read address FFFFFFFFFFFFFFFF)
-Circular counterclockwise = Code: C0000005 (Access Violation - tried to read address [random])

Mouse movement slightly delayed:
-Horizontal = speed-up, but Doomguy stands still
-Vertical and circular = always different results
```

3. Speedometer
It rapidly changes between 1 and 151

4. vid_fps
See video https://youtu.be/DEAgWXTFBAk
_Caution: the video may cause nausea._

5. If [AddEventHandlers = "PB_EventHandler"] is commented out, the bug is gone

**Comment by JMartinez9820** [comment] 2020-05-19 00:36
Thanks for reporting that the PB_EventHandler is possibly causing the problem. I will possibly make a hotfix for this on the Discord server, but I'm wondering what PB_EventHandler does and what it's purpose is. I'm going to speak to the devs to find out.

**Comment by JMartinez9820** [comment] 2020-05-19 01:09
@lord-andre @SyborgMars54 @funnymanDELUXE I've just finished the hotfix to fix this error. However, I will not push this fix to my branch yet. I've just got an answer from devs, PB_EventHandler is a handler that looks for player movement, and executes code as a response. That is why I'm not pushing this to my branch. Please kindly be patient for an official fix, and use this until the time has come.
https://mega.nz/file/buB2gIrC#BIKeuRkDivB-SiGDiI_C45SPWA1At7jEklb7QaH58QA

**Comment by Cacodemon345** [comment] 2020-05-19 05:45
Why GZDoom lacks protection against mod bugs is beyond baffling...

**Comment by Cacodemon345** [comment] 2020-05-19 10:19
Could you guys post this issue as a bug report in the ZDoom Forums too?

**Comment by SyborgMars54** [comment] 2020-05-19 11:04
Why if it is only one happening with nothing else but this mod?

**Comment by Cacodemon345** [comment] 2020-05-19 13:38
The bug is messing up the internals of GZDoom. That's why.

**Comment by SyborgMars54** [comment] 2020-05-19 14:09
OH SHIT

**Comment by Cacodemon345** [comment] 2020-05-21 13:19
On another note: Try enabling PB_EventHandler and start GZDoom with `vm_jit` turned off.

**Comment by lord-andre** [comment] 2020-05-21 22:05
I can gladly open a thread in the gzdoom forum. Can you give me more information about what is meant by the "internals of GZDoom"? So that I can explain it better there.

With `PB_EventHandler ` enabled and `vm_jit` off, the bug is still there.

**Comment by Cacodemon345** [comment] 2020-05-22 05:25
It messes up the lockstep timer GZDoom uses for its gameplay ticks. It also messes up the input system. And is partly hardware-specific.

Also make sure you post your system specs and config ini file there too.

**Comment by SyborgMars54** [comment] 2020-05-22 06:01
interesting?

**Comment by JMartinez9820** [comment] 2020-05-23 04:50
> With PB_EventHandler enabled and vm_jit off, the bug is still there.

I guess it's either related to either PB_EventHandler, hardware or the GZDoom engine's melt screen effect itself. My only choice is to switch the melt effect for the other effects or disable it, or use the hotfix that I made (Warning: disables PDA).
https://mega.nz/file/buB2gIrC#BIKeuRkDivB-SiGDiI_C45SPWA1At7jEklb7QaH58QA

**Comment by Xeno1979** [comment] 2020-05-23 11:44
Had that issue too, the hotfix solves it for me. great job!

**Comment by Cacodemon345** [comment] 2020-06-16 17:48
Did you guys open the issue at the ZDoom Forums yet?

**Comment by SyborgMars54** [comment] 2020-06-22 05:48
When yo mean by open the issue who was this directed at the devs or just anyone else experiencing the issue?

**Comment by Cacodemon345** [comment] 2020-06-22 08:17
What I meant is that the issue could be reported in the ZDoom Forums so that we can get guidance on how to fix the issue.

**Comment by SyborgMars54** [comment] 2020-06-25 04:19
well i haven't reported it to zdoom forums?

**Comment by Cacodemon345** [comment] 2020-07-26 15:56
Make sure the graphics drivers have been updated and then check if this bug still exists.

**Comment by SyborgMars54** [comment] 2020-07-29 03:24
well i have updated my driver and it still exists

**Comment by SyborgMars54** [comment] 2020-07-29 03:24
i reckon it is a form of memory leak

**Comment by SyborgMars54** [comment] 2020-07-29 03:24
but thats just a theory

**Comment by scaryred24** [comment] 2020-07-29 03:56
Keep the responses down to one post as much as possible. This bump is not needed. Also will not accepting any theories. Either it is or its not. You should be taking caco's advice as he is one of the two who has committed to this who also has ties with development with gzdoom. I cant stress this enough.

**Comment by JMartinez9820** [comment] 2020-07-29 03:59
I have updated my fix to be more compatible with the latest commit. This issue seems to be hardware related to some extent. We still haven't got an official response on what's causing this. If there is no response or if the team can't replicate this, then this issue may never be fixed. Load this after PB in the load order. This fix will also disable the PDA, and will stay as an add-on for the time being. My only other suggestion is to change the screen wipe style to Crossfade, Burn, or None in the Display Options.
https://mega.nz/file/nuJXRQbJ#2xGgNtksSH3L6CcfeGFdFkMQAvqcRmRwoZzpULOhHh4

**Comment by SyborgMars54** [comment] 2020-07-30 04:17
well i guess i could try to report the issue on the zdoom forums.

**Comment by SyborgMars54** [comment] 2020-08-14 02:01
just a bit nervous to report it cause i don't how to construct the sentence on what to say.

**Comment by JMartinez9820** [comment] 2020-09-25 16:56
I'm still unable to replicate this issue. This may need to be closed if this can't be resolved.

**Comment by SyborgMars54** [comment] 2020-09-26 07:36
crap

**Comment by JMartinez9820** [comment] 2020-09-26 12:11
Sorry. Either use the hotfix I linked, or switch the screenwipe style to Crossfade, Burn or None.

**Comment by Cacodemon345** [comment] 2020-09-26 17:35
@lord-andre You still in here?

**Comment by Cacodemon345** [comment] 2020-09-27 03:40
So I decided to open the bug report myself in GZDoom and it has been left on hold (not closed). So fixing this issue or waiting for the explanation is going to wait.

**Comment by lord-andre** [comment] 2020-09-27 21:55
Hello everyone. Sorry I was gone for so long. Health problems... 

I have tested the latest Pb version and GZDoom 4.4.2 
The error still occurs for me. I was able to test it on my brother's pc, he has the same bug. 
I will post his hardware specifications here and in the ZDoom Forum later.

I will post my crash reports and specs in the ZDoom Forum.
Here is the link: [https://forum.zdoom.org/viewtopic.php?f=53&t=69993](https://forum.zdoom.org/viewtopic.php?f=53&t=69993)

**Comment by JMartinez9820** [comment] 2020-09-28 00:19
For those still experiencing this issue, I would recommend switching the screen wipe style to Crossfade, Burn or None in the Display Options, or use this [hotfix](https://drive.google.com/file/d/1DHR38uYWWUtrJIKKBbd0JlEa0ocuKYQz/view?usp=sharing) that I just updated. Just a note though, the hotfix will disable the PDA. Its unknown is this issue will be fixed or not, so pick your poison.

**Comment by Cacodemon345** [comment] 2020-09-28 15:53
I found this in the crash reports:
```Incorrect data format for conversation script in TITLEMAP.```
Any idea? The whole DIALOGUE text file inside the titlemap.wad only consists of 2 bytes and is empty otherwise.

**Comment by lord-andre** [comment] 2020-09-30 11:45
Hi.
@Cacodemon345 
This message is displayed because I still had the developer options on. (`Developer 2` [Show warnings] in autoexec.cfg) 

I have now been able to further isolate the problem. I wondered why my brother had the same problem, but almost no one else.
The only hardware we both have is the mouse. After some testing on 6 pc's and several mice I can say the following:

It is indeed due to some mice. The hardware itself, not the drivers.
The following 2 I could find out as a source of error: 
 -Mad Catz M.M.O. 7 (My mouse)
 -Sharkoon Fireglider Black

@funnymanDELUXE & @SyborgMars54 
Which mouse do you use? Can you test another one?

---

I have checked the timeline to see from which commit the error occurs. 
Dec 20, 2019
- Commit 27fc7e649e91ac33f29849cc42239d4e2f56d702 and before = OK
- Starting with Commit 4b581eff3a94b5ef8ab7b2c9e793fcb2c1966323 the error is then included.

I then played around a bit in PBPDA.zc. If I comment out line 830, my mouse works too. Does that help?
But I don't really understand what I am doing ;-) And of course the PDA won't work anymore.
Line 830: `SendNetworkEvent("input",e.mouseX, e.mouseY,int(mouseinput));`

Reports from 2 other Pcs
[CrashReport.zip](https://github.com/pa1nki113r/Project_Brutality/files/5305153/CrashReport.zip)

**Comment by Cacodemon345** [comment] 2020-09-30 12:26
What are the manufacturers of the mice?

**Comment by SyborgMars54** [comment] 2020-09-30 13:39
well mine is a razer deathadder elite

**Comment by Cacodemon345** [comment] 2020-09-30 13:41
Try disabling the Razer driver and then check.

**Comment by SyborgMars54** [comment] 2020-09-30 13:44
how do i do that?

**Comment by Cacodemon345** [comment] 2020-09-30 14:23
Another option is to check what kind of mice causes problems.

**Comment by lord-andre** [comment] 2020-09-30 15:35
I've updated the list of mice in the post above

All 3 mice are programmable. The other ones that I tested and that worked were very simple or cheap mice.

While testing, I turned off the Internet connection so that Windows wouldn't install drivers by itself.

**Comment by Cacodemon345** [comment] 2020-10-01 07:20
Now try testing with the `in_mouse` CVAR. Try starting GZDoom with PB with `in_mouse` set to values ranging from 0 to 2 and tell me the results.

**Comment by lord-andre** [comment] 2020-10-01 12:05
`in_mouse 0` = Crash
`in_mouse 1` = no Crash
`in_mouse 2` = no Crash
`in_mouse 3` = Crash

**Comment by Cacodemon345** [comment] 2020-10-01 13:54
Can you try checking the GZDoom devbuilds and see if the issue is fixed? There was some changes to how mouse works so that might help.

**Comment by lord-andre** [comment] 2020-10-01 14:06
I tested `gzdoom-x64-g4.5pre-209-g2cb1438f9`. (Date: Oct 01 2020 11:12:15)
No changes for me

**Comment by Cacodemon345** [comment] 2020-10-01 15:36
Can you try with this with Vanilla Doom and see if the problem persists?
Note: This must not be unzipped and must be loaded directly instead.
[MouseBug.zip](https://github.com/pa1nki113r/Project_Brutality/files/5313173/MouseBug.zip)

**Comment by lord-andre** [comment] 2020-10-01 21:03
I tested it. Almost the same behavior. Got 2 new messages:

`TryRunTics: lowtic <gametick`
With this message, GZDoom was lagging like hell. The picture was no longer building up correctly and the console drew "streaks". Unfortunately I couldn't take a picture of that or get a crashlog.

`GetPacket: NOTINITIALISED`
new message, but still behave the same.

Input Value ranges from -164 to 180 for the first digit and
second digit: -25 to 25

[CrashReport_MouseBug.zip](https://github.com/pa1nki113r/Project_Brutality/files/5314721/CrashReport_MouseBug.zip)

**Comment by Cacodemon345** [comment] 2020-10-02 07:26
Try running this artifact (hint: copy the files as is into the GZDoom devbuilds directory and run the executable) and see if the bug still happens. If it doesn't happen I will push a fix into the upstream GZDoom repository.

https://github.com/Cacodemon345/gzdoom/suites/1277364779/artifacts/19748946

**Comment by lord-andre** [comment] 2020-10-02 20:16
Sorry, no changes. Still the same bug.

**Comment by Cacodemon345** [comment] 2020-10-03 06:17
I will try pushing a mod side fix at a later time.

**Comment by Cacodemon345** [comment] 2020-11-20 17:22
Test my branch. I finally got around to pushing the fix.

**Comment by Cacodemon345** [comment] 2021-01-18 10:23
Download the GZDoom dev build of Jan 19 when it becomes available. There is a memory corruption fix in the latest commit of GZDoom.

**Comment by lord-andre** [comment] 2021-02-03 23:10
I tested the developer versions from January 19 and February 03. No changes.

If I change in line

830    `if (gamestate == GS_TITLELEVEL || gametic <= 1) return false;`

the number 1 to e.g. 300, then the error does not occur at the first start / load. so 1 tic seems to be not enough.

Does the gametic keep running after the first start? Because if I load a savegame afterwards, gzdoom crashes again nevertheless (because the gametic is then over 300?)

Are there other time units in Doom? Is it possible to start and use a separate timer for the PDA?

**Comment by Cacodemon345** [comment] 2021-02-04 03:54
The gametic continues running from the time the game is started.

**Comment by Cacodemon345** [comment] 2021-02-04 16:04
It looks like this bug will have to be checked by someone who can compile GZDoom from source code with VS2019 using the debug builds.

**Comment by JMartinez9820** [comment] 2021-11-29 17:51
This issue will be closed for the time being due the lack of a response within the past 9 months.

**Comment by JMartinez9820** [comment] 2022-04-15 00:21
This issue will be closed for now due to no responses and a lack of feedback.

**Closed by JMartinez9820** 2022-04-15 00:21 UTC
Labels: bug, question

**Comment by lord-andre** [comment] 2022-05-09 23:57
Hello together!
I now have a new PC, with new mouse. (Cheap Medion mouse)

Rough specification of the PC:
Win 11 Home Version 21H2
CPU: Intel i7-12700K
GPU: NVIDIA 3070 Ti
32Gb RAM

The problem still persists. The only difference is that the new version of GZDoom & PB 3.0 (including staging) crashes more frequently with no error messages.
But I have an error message which I attach here.

To clarify, I personally don't mind this error as I just keep the mouse still or turn off the screen melt effect.

I just wanted to give input again.
[CrashReport.zip](https://github.com/pa1nki113r/Project_Brutality/files/8656049/CrashReport.zip)

**Comment by JMartinez9820** [comment] 2022-05-10 00:05
This bug will still won't be fixed, which is why this is closed. You're better asking either Cacodemon345 or the GZDoom team regarding this

**Comment by JMartinez9820** [comment] 2022-05-10 00:09
My suggestion is to see if this GZDoom version has less frequent crashes:
https://github.com/drdteam/gzdoom-gles/releases/tag/gles4.6.1

Other options would be trying the latest development versions of GZDoom, and switching renderers, particularly with OpenGL, Vulkan or OpenGL ES. Otherwise, change the screen transition effect to something else other than melt.

**Comment by lord-andre** [comment] 2022-05-10 00:27
I wrote specifically that the error does not bother me personally. I just wanted to give input so that maybe someday the error can be found and solved ^^

Your suggested version behaves in all render options the same. Whether OpenGl, Vulkan, Softpoly or OpenGL ES.

Setting the screen transition effect to "none" helps of course!

Again, I just wanted to help.

**Comment by JMartinez9820** [comment] 2022-05-10 00:46
Sorry if this bug has been bothering you. Unfortunately there is nothing I can do because of the limitations between PB and GZDoom. My suggestion is to contact Cacodemon345 (if he answers because he is busy with life iirc) if possible. Otherwise, this bug will not be fixed and I may lock this conversation.
