### ISSUE TITLE
Carbine bug. Showing carbine when had LMG

### ISSUE THREAD

**Issue by rasyidridha532** [pa1nki113r/Project_Brutality#446] opened 2020-08-04 14:21 UTC
I had an LMG but when i try to change weapons to DMR and change again to LMG it show carbine but it skipped to LMG.

[carbine bug.zip](https://github.com/pa1nki113r/Project_Brutality/files/5022630/carbine.bug.zip)

**Comment by JMartinez9820** [comment] 2020-08-04 14:46
@rasyidridha532 Duplicate of #369. This is known, possibly a checker for upgrades was added but it's very minor. Next time please check for other issues, opened or closed, before posting and issue of the same topic.

**Comment by goldenmob72** [comment] 2020-08-04 14:49
^ Closing this issue now

**Closed by goldenmob72** 2020-08-04 14:49 UTC

**Comment by rasyidridha532** [comment] 2020-08-04 14:51
Alright. I check out same issues first before i make a report. Thanks.
