### ISSUE TITLE
Duel wielding 

### ISSUE THREAD

**Issue by cacy17** [pa1nki113r/Project_Brutality#204] opened 2019-08-05 20:30 UTC
Please double the clips of weapons that are being duel weld.

**Comment by scaryred24** [comment] 2019-08-06 14:31
Actually what it does right now is it only counts for how many is in a clip or mag. It takes 2 shots to drop it down by 1 in the hud. This will be looked into. Thank you for the bug report.

**Comment by JMartinez9820** [comment] 2020-07-26 07:02
Dual wielding system has been officially overhauled, although the double ammo hasn't been implemented yet. This will be taken care of later on. This is also a duplicate of your previous issue, #155.

**Closed** 2020-07-26 11:55 UTC
Labels: bug
