### ISSUE TITLE
Level enhancements dont work

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#301] opened 2020-01-02 21:58 UTC
Ive toggled the level enhancements on and off, they still dont show up

**Comment by BenjaminZuriel** [comment] 2020-01-02 22:06
The Level enhancement scripts were removed.

**Comment by JMartinez9820** [comment] 2020-01-02 22:12
Please look at the active or closed issues before posting an issue, this is an obvious duplicate of #263. Map enhancements are officially scrapped, and this issue should be closed.

**Closed** 2020-01-02 22:51 UTC
