### ISSUE TITLE
Disabling zombie grenades does nothing.

### ISSUE THREAD

**Issue by tochjunin** [pa1nki113r/Project_Brutality#964] opened 2022-10-09 17:42 UTC
I tryed to disable grenades in the: PROJECT BRUTALITY > Global Settings > Configure Monster Abilities > No Zombies Grenades
Setting it to yes or no, zombie still throws grenades normally

**Comment by JMartinez9820** [comment] 2022-10-09 21:11
Duplicate of one of the issues in #813. Please look at current open and closed issues before reporting.

**Closed by JMartinez9820** 2022-10-09 21:11 UTC
