### ISSUE TITLE
Using a Zombie as a meatshield crashes the game

### ISSUE THREAD

**Issue by LucianM1** [pa1nki113r/Project_Brutality#171] opened 2019-06-29 18:31 UTC
The game will crash after you throw the zombie off of you.
(VM EXECUTION ABORTED)
https://youtu.be/g-jBn6ZFmMs

**Comment by MekBoss** [comment] 2019-07-02 22:04
Check pined messages in hotfix channel of PB discord server. There are fix for it.

**Comment by JMartinez9820** [comment] 2019-12-23 23:52
This issue is actually a duplicate of #102.

**Comment by JMartinez9820** [comment] 2020-04-17 07:55
This issue can be closed as it has been fixed.

**Closed** 2020-04-19 17:19 UTC
Labels: bug
