### ISSUE TITLE
Deagle Ammo

### ISSUE THREAD

**Issue by goldenmob72** [pa1nki113r/Project_Brutality#330] opened 2020-01-29 01:58 UTC
When using a Single DEagle it can fire up to 12 Bullets , When Dual Wielding/Akimbo DEagles you can still fire 12. It should fire 24 when Dual wielding/Akimbo DEagles

**Comment by JMartinez9820** [comment] 2020-01-29 02:39
The dual Deagles do fire 24 rounds, but due to dual wielding being tied under one script (or it's not defined yet), it will display the number of rounds from a single Deagle. So in my opinion, this is a duplicate of #204. Hopefully, this gets fixed at a later point in development, thank you for reporting this though.

**Comment by pa1nki113r** [comment] 2020-04-21 23:46
Intended feature for right now. We'll definitely have an improvement for it later down the line. Closing for now.

**Closed by pa1nki113r** 2020-04-21 23:46 UTC
Labels: minor priority
