### ISSUE TITLE
Disabled Weapons Still Spawn

### ISSUE THREAD

**Issue by BrandinIX** [pa1nki113r/Project_Brutality#357] opened 2020-04-07 00:55 UTC
Weapons such as the Nailgun, Auto Shotgun, SMG, and Dark Matter Rifle still spawn even if they are disabled in the menu. Also the Shotgunguys tend to die on their own for some reason, could be because of their new behavior.

**Comment by JMartinez9820** [comment] 2020-04-07 01:07
As for disabled weapons, this is due to the overhauled weapon scripts. Also, do you have any ways to reproduce the Shotgunguys dying on their own? I've never noticed that on my end. Thank you for reporting this, however, at this time, these are not a big priority.

**Comment by BrandinIX** [comment] 2020-04-07 01:13
Wish I could provide a screenshot but earlier this morning on The Waste Tunnels, a Shotgunguy in front of the the red key door randomly died when I walked in front of him, The others issues occurred a couple minutes ago while playing through Eday.

**Comment by popguy12** [comment] 2023-06-25 22:31
Closing due to menu overhaul removing these options or fixing them

**Closed by popguy12** 2023-06-25 22:31 UTC
Labels: minor priority
