### ISSUE TITLE
am_showkeys_always not working

### ISSUE THREAD

**Issue by lumin8shun** [pa1nki113r/Project_Brutality#591] opened 2021-01-01 05:05 UTC
GZDoom 4.5
Keys pick up fine on Automap when am_showkeys_always enabled.

GZDoom 4.5 + Project_Brutality 3.0 Master branch (2020-12-27)
Keys don't show up on Automap when am_showkeys_always enabled.

Previous issues that have been closed:
#140 
#486

**Comment by JMartinez9820** [comment] 2021-01-01 06:33
@lumin8shun You just mentioned issues that are similar to this one, as a result this issue is a duplicate of those. Take a look at the issues tracker, open or closed, before posting a new issue.

**Comment by D3X1KAXYZ** [comment] 2021-01-01 06:48
@JMartinez9820 closed usually means resolved. This issue doesn't appear to have ever been resolved.

**Comment by D3X1KAXYZ** [comment] 2021-01-01 06:56
Are you able to reopen old issues even if you didn't create them?

**Comment by JMartinez9820** [comment] 2021-01-01 07:04
The original issue owners have to reopen them.

**Comment by JMartinez9820** [comment] 2021-01-01 07:08
Btw, I just fixed this issue on my end. It turns out that these lines of code were causing it, this is just an example. 
``ACTOR RedKeyCard : CustomInventory Replaces RedCard``

I just removed the CustomInventory Replaces portion of those and it seems to have fixed the issue:
``ACTOR RedSkullKey : RedSkull``

Anyways, will be pushing the fix onto my branch tonight. But still... How can I be so stupid with unresolved issues being closed and I considered them duplicates? I really feel like hurting myself right now...

**Comment by lumin8shun** [comment] 2021-01-01 10:34
Thanks guys! Love your work!

**Comment by lumin8shun** [comment] 2021-01-01 11:27
@JMartinez9820
I've made the changes in DECORATE that you've commit in your branch for this issue on my own DECORATE.
(eg. ACTOR BlueKeyCard : CustomInventory Replaces BlueCard changed to ACTOR BlueKeyCard : BlueCard)

From that change, It shows the key in automap as black (where I think its supposed to do the colour of the respective key).
I also found that when picking up the key, it doesn't add to my inventory and softlocks me in levels as unable to open any doors.

Unless there is a change outside of this commit that resolves the above?
(I'm new to bug reporting\testing so please excuse my lack of understanding)

**Comment by JMartinez9820** [comment] 2021-01-01 15:32
Oh, really? If that's the case then I may have to revert the change

**Comment by JMartinez9820** [comment] 2021-01-01 15:50
@lumin8shun 
Also, my changes seem to have worked. Did you download my branch? If not, then download it: https://github.com/JMartinez9820/Project_Brutality/tree/JMBranch

**Comment by JMartinez9820** [comment] 2021-01-01 17:22
Unfortunately, I'm going to revert the fix. The sound for some reason broke, so this is confirmed to be unfixable. This is not a top priority anyway, I'm sure that other mods that replace the keys with their own have this error too.

**Comment by lumin8shun** [comment] 2021-01-02 00:10
No worries @JMartinez9820 , thanks for your efforts.
I'll keep this issue open. Happy to do testing of any commits related to the matter if you find any solutions in the future.

**Comment by popguy12** [comment] 2021-12-23 11:11
i think this can be closed now, since the keys were redone in ZScript and fixed up

**Closed by popguy12** 2021-12-23 11:11 UTC
Labels: minor priority

**Comment by JMartinez9820** [comment] 2022-03-14 07:34
Update on this issue: I can confirm that any KeyCard or KeyCard base that uses CustomInventory to replace the original is the reason why. This will not be fixed, as I see that other mods have this issue too (Tested with EVP and Brutal Doom Platinum). It's unfortunately a limitation that CustomInventory has. This will NOT be fixed.
