### ISSUE TITLE
VM execution aborted while picking up the SMG

### ISSUE THREAD

**Issue by RedLightPumpkin** [pa1nki113r/Project_Brutality#298] opened 2019-12-24 03:35 UTC
![abc](https://user-images.githubusercontent.com/47189037/71391985-b5cd2080-2606-11ea-981b-59f7b3248c45.png)

**Comment by JMartinez9820** [comment] 2019-12-24 03:40
This issue is a duplicate of #292, therefore this will not be logged. However, take a look at the PDA Branch, as it has an update to fix this issue. When reporting an issue, please take a look at the issues that are currently active or closed before creating to prevent duplicates from happening.
https://github.com/pa1nki113r/Project_Brutality/tree/pdabranch

**Comment by JMartinez9820** [comment] 2019-12-24 16:05
Since this issue is a duplicate, it can be closed.

**Closed** 2019-12-24 17:04 UTC
