### ISSUE TITLE
Death messages don't respect engine player gender settings

### ISSUE THREAD

**Issue by MadestMadness** [pa1nki113r/Project_Brutality#257] opened 2019-11-15 05:25 UTC
Some death messages respect GZDoom's player gender settings, like "Maddie killed herself." while others don't, like "Maddie got his face splattered on the wall by a Zombie Shotgunner."

**Comment by JD531** [comment] 2019-11-15 05:52
An oversight. Can be easily fixed by changing the enemy's obituaries his / him with %p and %h respectively. Currently a minor priority since monster overhaul is being implemented very slowly.

**Comment by scaryred24** [comment] 2019-11-28 01:29
Minor oversight. Will be corrected once monster overhaul takes into full effect.

**Comment by JasonM2396** [comment] 2020-04-29 01:24
This pull request can be closed. It is confirmed to be fixed after the Shotgun Guys and Riot Shield Troopers were overhauled. The death message on Shotgun Guy now says "Playername was blasted away by a Zombie Sergeant."

**Closed** 2020-04-29 03:05 UTC
Labels: minor priority, oversight
