### ISSUE TITLE
ZMove Mod makes the movement clunky. What is the best option to emulate Brutal Doomv21 movement physics?

### ISSUE THREAD

**Issue by BlyatSlayer** [pa1nki113r/Project_Brutality#287] opened 2019-12-15 06:37 UTC
only noticed it now. yeah it feels clunky.

**Comment by JMartinez9820** [comment] 2019-12-15 06:44
PB uses an older version of ZMovement, it will be updated and fine-tuned at a later point in development. However, this issue is also a duplicate of #242, therefore, this will not be logged at this time.

**Comment by JMartinez9820** [comment] 2019-12-15 06:45
Pa1nki113r himself did have some settings he did recommend here though:
https://cdn.discordapp.com/attachments/628066836751319060/628402844957016094/unknown.png
https://cdn.discordapp.com/attachments/628066836751319060/628402950120931358/unknown.png

**Comment by pa1nki113r** [comment] 2019-12-23 03:38
Going to be updating zmovement to the latest version soon

**Comment by goldenmobster** [comment] 2020-01-17 17:20
Closing for now

**Closed by goldenmobster** 2020-01-17 17:20 UTC
