### ISSUE TITLE
Plasma Gun holstering animation bugged

### ISSUE THREAD

**Issue by L4Y-Duke** [pa1nki113r/Project_Brutality#250] opened 2019-11-06 19:00 UTC
The holstering animation for the Plasma Gun (I forget the exact name, it's the one with the Lightning Gun upgrade option) is bugged out. 
Instead of holstering the gun, the animation for dual-wielding it and firing the right-hand weapon plays.
The problem may have arisen because I found the Lightning Gun upgrade for the weapon before acquiring the weapon itself. Finding a copy of the weapon later did not fix the issue.

**Comment by JMartinez9820** [comment] 2019-11-06 19:05
The Plasma Rifle being taked about here is the M2 Plasma Rifle. However, this issue is a duplicate of #182. Take a look at pull #247, this will resolve that issue.

**Closed** 2019-11-06 20:23 UTC
