### ISSUE TITLE
Plz Fix!!!1 

### ISSUE THREAD

**Issue by R4bb1tB0y** [pa1nki113r/Project_Brutality#576] opened 2020-12-15 16:54 UTC
I seriously can't play this anymore, every time i get killed and try to respawn the game crashes or my character simply doesn't want to move, the game also freezes A LOT, and the weapons sometimes start to do a reload animation indefinitely, and the only way to fix this is to drop my weapon.

**Comment by JMartinez9820** [comment] 2020-12-15 17:43
Which GZDoom version are you using? Also, the reload animation glitch is fixed on my branch. Check pull #566 or find JMbranch3

**Comment by RealRexen** [comment] 2020-12-15 21:21
There shouldn't be any (major) freezing, the only freezing I get is when a surplus of monsters get alerted at once (like 200+) and it doesnt last long, usually a second or two even then its mostly just frame drops . This happens on GZDoom 4.5 and 4.6pre. Also more details help, like what where you trying to do before you can no longer move, so its easier to check and try to reproduce.  Also it will be nice to know how recent your version is since the issue(s) could of been fixed

**Comment by D3X1KAXYZ** [comment] 2020-12-17 18:16
Please be more descriptive with Issue Titles. Titles like Plz Fix!!!1 or HELPPPPPPPP do not help us nor will it help you in most situations. Many large support teams will usually ignore these kinds of titles or set them aside til later. Also anyone browsing the issue reports for help with a similar issue will have a harder time finding this.
perhaps try:
### Game crashes on re-spawn and Weapons infinitely reload.

**Comment by D3X1KAXYZ** [comment] 2021-01-29 23:24
This issue appears to have fixed, if it has not, feel free to reopen this issue or join us on discord: https://discord.gg/2hJxXPc
For now, I shall close this issue.

**Closed** 2021-01-29 23:24 UTC
