### ISSUE TITLE
Nailgun Harpoon Mode ReloadBug

### ISSUE THREAD

**Issue by popguy12** [pa1nki113r/Project_Brutality#394] opened 2020-06-04 20:46 UTC
Reloading the Nailgun in Harpoon mode can be done infinietly as long as the player has no more ammo in reserve, and if the gun isnt already full

**Comment by JMartinez9820** [comment] 2020-06-04 21:00
Steps to replicate?

**Comment by JMartinez9820** [comment] 2020-06-04 21:08
Update: Was able to replicate it. Pressing reload while in Javelin mode with no reserve ammo left. Very minor, I'm going to see what I can do about it.

**Comment by JMartinez9820** [comment] 2020-06-05 00:26
Before I implement this, can you see if this fix works? I've seen to have fixed the infinite reloading problem when using Javelin mode and the reload key is pressing when having no reserve ammo (NewClip) left.
https://mega.nz/file/ymx3DToQ#87ygb5ZosNGBX0Zv941_192AULmUD61aJrTEXFHf8Jo

**Comment by popguy12** [comment] 2020-06-05 15:56
that fix seems to work fine, but now im noticing that it doesnt allow reload unless you have at least 20 bullets

**Comment by JMartinez9820** [comment] 2020-06-05 16:19
That was actually my original intention. If less than 20 rounds were detected on reserve, wouldn't reload. Now I changed it so only one is needed since I thought it may have been a bad idea. I've already implemented the fix on my pr, #375 .

**Comment by JMartinez9820** [comment] 2020-06-05 16:24
Small update: The Nailgun in Javelin mode not reloading if less than 20 rounds in the reserve seems to be intentional in the weapon's code since each javelin uses 20 rounds.

**Comment by goldenmob72** [comment] 2020-07-26 11:59
Has this been resolved ?

**Comment by Cacodemon345** [comment] 2020-07-31 17:42
This seems to be apparently resolved. Closing for now.

**Closed** 2020-07-31 17:42 UTC
Labels: bug

**Comment by JMartinez9820** [comment] 2020-08-06 21:52
I can confirm that this bug still exists in latest build. I have fixed it in pull request #445. This issue can be re-opened for now, and can be closed again once #445 is merged.
