### ISSUE TITLE
Barrel explosion crash.

### ISSUE THREAD

**Issue by BrandinIX** [pa1nki113r/Project_Brutality#288] opened 2019-12-16 04:49 UTC
Sometimes when you throw a barrel, the game will crash forcing you to CTRL, ALT, DEL out of it and close the game in Task Manager. I don't know if this has something to do with the build itself or it depends on your computer.

**Comment by JMartinez9820** [comment] 2019-12-16 05:14
Duplicate of #205. This bug is actually temporarily fixed in the new versions, make sure to start a new game from the beginning. Dropping it normally is fine, but spam dropping (grabbing the barrels and dropping multiple times in fast motion) or dropping barrels too often may crash the game.

**Comment by BrandinIX** [comment] 2019-12-16 20:18
Its not dropping barrels, its throwing them, I threw one once and it crashed the game.

**Comment by lord-andre** [comment] 2019-12-17 17:41
Picking up, throwing and placing back on the ground works fine.
However, if you immediately switch to another weapon after throwing/dropping, using the number keys, the game crashes.

Error message for throwing:
```
VM execution aborted:  BarrelThrower.StateFunction.66 called without valid caller. BarrelThrower expected
Called from PSprite.Tick at gzdoom.pk3:zscript/actors/player/player.zs, line 2565
Called from PlayerPawn.TickPSprites at gzdoom.pk3:zscript/actors/player/player.zs, line 481
Called from PlayerPawnBase.PlayerThink at Project_Brutality-master.zip:zscript/playerpawn.zc, line 183
Called from state BarrelThrower.66
Called from PSprite.SetState [Native]
```

Error message for placing back:
```
VM execution aborted:  BarrelThrower.StateFunction.127 called without valid caller. BarrelThrower expected
Called from PSprite.Tick at gzdoom.pk3:zscript/actors/player/player.zs, line 2565
Called from PlayerPawn.TickPSprites at gzdoom.pk3:zscript/actors/player/player.zs, line 481
Called from PlayerPawnBase.PlayerThink at Project_Brutality-master.zip:zscript/playerpawn.zc, line 183
Called from state BarrelThrower.127
Called from PSprite.SetState [Native]
```

Should i also post this in #205 ?

**Comment by lord-andre** [comment] 2020-01-12 01:39
The bug seems to be fixed now. The crash caused by the fast weapon change no longer happens, or ist possible.

**Closed** 2020-04-21 23:38 UTC
Labels: bug
