### ISSUE TITLE
Character not moving

### ISSUE THREAD

**Issue by Vlad23790** [pa1nki113r/Project_Brutality#1191] opened 2023-10-22 08:02 UTC
My character not moving Fix This Bug I can't move.

**Comment by inkoalawetrust** [comment] 2023-10-22 08:03
Maybe actually describe something ? Like, what version are you using for example, how did you start the mod up ?

**Comment by JMartinez9820** [comment] 2023-10-22 13:03
Duplicate of the same thing that's been said a lot. Delete your GZDoom.ini and it should fix it

**Comment by Vlad23790** [comment] 2023-10-23 12:48
> Maybe actually describe something ? Like, what version are you using for example, how did you start the mod up ?

I just send zip of project brutality to gzdoom

**Comment by generic-name-guy** [comment] 2023-10-23 14:00
Make sure to update to the PB_Staging branch so this problem doesn't happen again.

**Closed** 2024-04-02 23:08 UTC

**Comment by Vlad23790** [comment] 2024-04-09 17:31
I solve this problem thank you all for say delete gzdoom ini

ср, 3 апр. 2024 г., 03:09 popguy12 ***@***.***>:
