### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Buckethell** [pa1nki113r/Project_Brutality#224] opened 2019-09-17 16:28 UTC
Giant blood steps appear when you walk on blood over the clean tiles

With an Heavy Plasma Gun equipped, the akimbo can be seen for a brief moment when you switch to other weapons (even if you don't have akimbo heavy plasma gun)

When the tip of the minigun is hot and you throw a granade, you can still see the hot sprite layer even when the minigun goes down

**Comment by JMartinez9820** [comment] 2019-09-21 17:59
The giant footsteps is a scale issue involving LegacyBlood and GreenBlood. The M2 Plasma Rifle bug is actually a duplicate of issue #182 . The Minigun layer is not a top priority to fix at this moment, since its a layer.

**Comment by goldenmobster** [comment] 2019-12-01 21:36
The Giant Bloody footprints have been resolved, and since The M2 Plasma Bug is a duplicate of #182 [What JMartinez mentioned] this issue can be closed because we have a duplicate of that issue.

**Closed by goldenmobster** 2019-12-01 21:36 UTC
