### ISSUE TITLE
New Barrel Bug

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#371] opened 2020-04-22 03:57 UTC
From today 21/04/20 

Also using Latest GZDoom 4.3.3 x64 and with ZDL

First Issue:If you try to grab a explosive barrel, this duplicates then blows.

How to do this, grab a berserk pack then grab a explosive barrel, this will instantly duplicates, making you throw a "ghost" barrel(or duplicated barrel),  then grabs the barrel you tried to grab in first place.

Second Issue: in the previous update(20/04/20) if you  grab and put back the barrel in their site(faster), your hands will dissapear, no more game crash(very rare when this happens, still), but your hands will dissapear and if you look down your legs, this will be missaligned, and actually, you can't do nothing for the same reason, you can't change weapons, anything.

i didn't tried the last one for the same reason of the first issue, also i didn't tried this with fire barrels, if it happens i'll update this.

**Comment by JMartinez9820** [comment] 2020-04-22 04:01
Known issue, I've done this before. This is because Meatshields and Barrels replace the partially replace the rifle. I can see them being overhauled because the code for them is pretty atrocious. Most of the time the game will fix itself when this happens. The code was like this:
Actor BarrelThrower: Rifle
Thanks for reporting this. However, it may take some time to fix this. Bugs take time to be fixed.

**Comment by Mr-Blazkowicz** [comment] 2020-04-22 04:13
Np

**Comment by Mr-Blazkowicz** [comment] 2020-04-22 04:21
Quick Update: both of the issues don't affect the fire barrel

**Comment by JMartinez9820** [comment] 2020-05-16 16:42
@Mr-Blazkowicz Does this error still persist in the latest version? Meatshields got a minor update in the latest commit based on the actor. Instead of being known as Actor BarrelThrower: Rifle, its now Actor BarrelThrower: PB_Weapon.  I just wanted to let you know just in case this error does persist in the newest version.

**Comment by Mr-Blazkowicz** [comment] 2020-05-17 00:46
hold on let me check it real quick

**Comment by Mr-Blazkowicz** [comment] 2020-05-17 00:53
nvm, i tested this on the build from the "vanilla zmovement" update, from like 25 days ago, and i can't fully test it because "double barrel bug", i will try it anyway if i can and ill let you know, also i noticed that some dead bodies like savage imps can be grabbed from the wall (when they die an lay on the wall), idk if this is mean to be like it is.

**Comment by JMartinez9820** [comment] 2020-05-17 01:08
I don't think the grabbing the dead body as a meatshield thing is intentional. Currently we haven't got to meatshields yet, so it's not really anything to take care of now since it's very minor. Probably when they get overhauled that will be fixed, right now it's nothing major.

**Comment by Mr-Blazkowicz** [comment] 2020-05-17 01:17
well, so far i tested the barrel grab with every gun, the "double barrel" bug only happens when you have the fist, if you have other any weapon and you grab a barreñ this will not happen, the barrel bug of course, but i saw another bug really interesting, if you have the dual revolvers and if you want to drop them, the game will crash, also the game crash from the barrel grab is no more, i'll try  with the other dual weapons and ill let you know if one of these crashes the game too.

**Comment by Mr-Blazkowicz** [comment] 2020-05-17 01:32
okay so, only the revolvers have the "drop" bug, if you drop the dual revolvers and if pick at least 1 of them, the game will freeze/crash

**Comment by JMartinez9820** [comment] 2020-05-17 02:38
> okay so, only the revolvers have the "drop crash" bug, if you drop the dual revolvers and pick up at least 1 of them, the game will freeze/crash

Duplicate of #215.

**Comment by Mr-Blazkowicz** [comment] 2020-05-17 21:40
okay so, should i delete the dual revolvers bug from here?

**Comment by goldenmob72** [comment] 2020-07-24 12:42
Yes

**Comment by JMartinez9820** [comment] 2020-08-08 04:52
This appears to be fixed in the newest commit. This issue cane be closed for now. If you encounter this again, just reopen this.

**Comment by Mr-Blazkowicz** [comment] 2020-08-08 06:29
The problem is still there, but only whe you don't have a weapon equipped(fist), i recently tried this in the latest build (new railgun update from today 7/08/20) tested on GZDoom 4.4.2 x64 with zdl.

**Comment by JMartinez9820** [comment] 2020-08-08 06:33
Oh I see. Sorry about that. Deleted prior message. This is not a top priority to fix at this moment. Barrels and meatshields may undergo major overhauls in the future.

**Comment by JMartinez9820** [comment] 2020-08-08 15:06
Can you show some detailed instructions on replicating this? I was unable to replicate it

**Comment by Mr-Blazkowicz** [comment] 2020-08-08 23:17
Here: https://youtu.be/qEv-3cD3IiM

**Comment by JMartinez9820** [comment] 2021-02-04 21:15
@Mr-Blazkowicz I was finally able to fix that barrel bug. Test out and check out pull #623 when you can. Here is also a link to the said [branch](https://github.com/JMartinez9820/Project_Brutality/tree/ChainsawFixes) that is going to fix it.

**Closed** 2021-03-01 03:01 UTC
Labels: bug
