### ISSUE TITLE
Super shotgun bug

### ISSUE THREAD

**Issue by 34-cyrpty** [pa1nki113r/Project_Brutality#384] opened 2020-05-04 14:14 UTC
Whenever i slice with the super shotgun i grow a third arm and slice with it. Is this a bug or its already planned to be fixed?

**Comment by JMartinez9820** [comment] 2020-05-04 14:16
It will be fixed soon, heck I might push a pull request right now. I've already fixed this, along with the Autoshotgun, Deagle and Dual Weild SMGs on my end.

**Comment by JMartinez9820** [comment] 2020-05-04 14:23
I forgot to mention this, but part of this is a duplicate of #194 .

**Comment by 34-cyrpty** [comment] 2020-05-04 14:23
sorry i havent realised it

**Comment by goldenmob72** [comment] 2020-05-04 15:27
Since this is Duplicate, I'm closing this issue

**Closed by goldenmob72** 2020-05-04 15:27 UTC
