### ISSUE TITLE
VM Execution Aborted : tried to read from address zero problem

### ISSUE THREAD

**Issue by BlyatSlayer** [pa1nki113r/Project_Brutality#282] opened 2019-12-11 15:05 UTC
Occurs randomly ( but mostly around 1-2 mins after playing ).
 Ran on GZDoom
![Screenshot_2019-12-11-22-49-04-342_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/58780717/70632954-afd05a80-1c6a-11ea-9708-cabfc5046029.png)
 version 4.2.4

**Comment by JMartinez9820** [comment] 2019-12-11 15:20
@BlyatSlayer Disable Motion Blur in the Project Brutality settings. It can be found in Project Brutality Settings -> Rendering Settings -> Motion Blur.

**Comment by BlyatSlayer** [comment] 2019-12-11 15:27
> @BlyatSlayer Disable Motion Blur in the Project Brutality settings. It can be found in Project Brutality Settings -> Rendering Settings -> Motion Blur.

It solves the zscript.zc line 615 problem, but a new VM execution error pops up
![Screenshot_2019-12-11-23-24-22-208_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/58780717/70634673-9da3eb80-1c6d-11ea-8d89-1491306855b2.png)

**Comment by JMartinez9820** [comment] 2019-12-11 15:39
Although that new issue right there is a duplicate of #209, you try this fix I made here. Load after PB.
https://mega.nz/#!7n4RQYiA!B4OKLBqtk7LhZxSm1w6HU8v3kSUFnh3KMe5ex8_haQk

**Closed** 2019-12-13 14:43 UTC
Labels: bug, duplicate
