### ISSUE TITLE
Boss brain

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#803] opened 2022-01-16 00:23 UTC
Levels that use the trick of surrounding a boss brain (John romeros head) with barrels and teleporting the player onto a barrel to blow them up to end the level don't work.  As soon as you start the map the barrels explode ending the level. Experimenting with doom builder I discovered if a teleport destination is overlapping a flaming barrel it causes it to explode ending the level. This didn't happen with older versions of PB over 4 months ago. Related to the recent barrel overhaul I guess.

**Comment by JMartinez9820** [comment] 2022-01-16 01:16
@TonyH1234 There is an option to disable random barrels, but as a cvar iirc. Barrels are going to be overhauled again later on, but converted to ZScript. The cvar is this:
pb_LuckyBarrels 0

You may need to start a new game or finish a level for this cvar to take effect.

**Comment by TonyH1234** [comment] 2022-01-16 03:43
Changed pb_LuckyBarrels to 0. Discovered other problems.  If a teleport destination is touching a boss brain, the level ends even with no barrels around. If the player teleports into a group of barrels, they don't blow up, he just gets stuck.

**Comment by JMartinez9820** [comment] 2022-01-16 05:45
@TonyH1234 You might want to ask PopeOfDope on Discord about this, since he coded in the barrels

**Comment by ehabibov** [comment] 2022-11-09 19:10
@TonyH1234 did you find the solution?) I couldn't figure out what exactly was the cause before your posts but still facing this generally on 31st/32th maps which is disappointing to skip that levels.

**Comment by TonyH1234** [comment] 2022-11-10 05:05
As far as I know, no solution yet. I haven't played a map like these for a while now so don't know if it's fixed with latest update.

**Comment by DemonSlayer1997** [comment] 2022-11-10 05:24
> As far as I know, no solution yet. I haven't played a map like these for a while now so don't know if it's fixed with latest update.

Wait for a complete overhaul of Icon of Sin as there is a complete mess in the code at the moment.

**Comment by ehabibov** [comment] 2022-11-16 21:33
Thanks.

I got some workaround meanwhile. When I face such levels (which has icon_of_sin_scream at 11th second and it finishes on its own), I just do (console)
`remove BossBrain`
at first level seconds to remove buggy head (actor) and just play. At level end player actually permanently dies stepping into final portal but instead I just do
`changemap map{nextMapNumber}`
So, these are actually cheats, but imo legal and level not missed.

**Comment by JMartinez9820** [comment] 2022-11-16 22:28
If I recall correctly, Hideous Destructor had a similar issue but they managed to fix it. I might try to contact one of the HDest devs to see how they fixed, or popguy would try something similar.

**Comment by JMartinez9820** [comment] 2023-02-10 23:34
This should be fixed now, I recently got a DM saying that the BrutalTeleportDest was causing the issue. That actor is now completely removed on my branch.

**Comment by JMartinez9820** [comment] 2023-02-26 21:23
@ehabibov @TonyH1234 
This will be fixed on my branch, I will post it here later and do some testing first.

**Comment by JMartinez9820** [comment] 2023-02-26 21:44
https://github.com/pa1nki113r/Project_Brutality/tree/JMartinez-OfficialBranch

Just pushed it now.

**Closed by JMartinez9820** 2023-02-26 21:44 UTC
Labels: help wanted, good first issue, question, Going to be fixed (Soon)
