### ISSUE TITLE
VM execution aborted: tried to read from address zero. In function parameter "target"

### ISSUE THREAD

**Issue by pizzasoda66** [pa1nki113r/Project_Brutality#313] opened 2020-01-13 07:22 UTC
I'm trying to play this mod but the game randomly stops working and I get this error message. I saw another thread with a similar issue with a supposed fix but no actual clear instructions were given. I know this is still in development but it's still irritating.

**Comment by JMartinez9820** [comment] 2020-01-13 07:32
Can you please share a screenshot of the issue? The team won't know what the issue is if you don't provide enough information.

**Comment by pizzasoda66** [comment] 2020-01-14 01:00
> Can you please share a screenshot of the issue? The team won't know what the issue is if you don't provide enough information.

Ok so I just recovered it to get a screenshot, played a bit, and never encountered this message again.. I did download a different version of GZdoom but I don't see how that could have fixed it. Of course, I can't play traditional mode without it crashing GZdoom

**Comment by scaryred24** [comment] 2020-01-14 04:54
> I did download a different version of GZdoom but I don't see how that could have fixed it.

Still missing details as jmartinez had said. Attach screenshot below and please specify what build of gzdoom you downgraded to and what version you were on that was causing the crashes.

**Comment by pizzasoda66** [comment] 2020-01-14 05:41
I originally used a development build of GZdoom with the label "gzdoom-x86-g4.3pre-660-ge3eae62af" but then switched to the 4.3.1 build available on the zdoom website (https://zdoom.org/downloads). As for the crashes, every time I try playing the traditional mode, the game crashes and I get this popup
![error](https://user-images.githubusercontent.com/30043107/72317227-8b4f1000-3666-11ea-81ec-390c4c4544b7.png)

**Comment by JMartinez9820** [comment] 2020-01-14 05:53
I don't what is causing GZDoom to crash on Traditional mode, but I heard that Traditional mode can be scrapped in the future, just like the Brutal Doom v21 class. No one really plays Traditional mode, so I can see it being scrapped. Traditional mode is not a top priority right now.

**Comment by scaryred24** [comment] 2020-01-14 05:58
We don't give support for git builds of gzdoom as we don't actively develop the mod with that in mind. Is 4.3.1 the build before these earlier crashes happens? Also is your pc able to run the 64 bit builds or you just choose to use the 32 bit ones?

**Comment by pizzasoda66** [comment] 2020-01-14 06:32
> Is 4.3.1 the build before these earlier crashes happens? Also is your pc able to run the 64 bit builds or you just choose to use the 32 bit ones?
The crashes still happened after I switched to 4.3.1. And it is.

**Comment by scaryred24** [comment] 2020-01-14 08:00
Will see what can be done about it. I can't be certain that it will be fixed at this current point of development as it may just go to waste as mentioned that the entire class would be removed at a later date. Will keep this open until either a fix is made or the class is entirely removed.

**Closed** 2020-01-14 08:31 UTC
Labels: minor priority
